name: "Build ðŸ”¨"

on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches: [ main ]

jobs:
  build:
    name: "Build ðŸ”¨"
    if: github.event.pull_request.draft == false
    runs-on: macos-15

    env:
      XCODE_VERSION: "16.4"
      TVOS_VERSION: "18"
      TVOS_SIMULATOR: "Apple TV 4K"
      FASTLANE_SKIP_UPDATE_CHECK: "1"

    steps:    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install SwiftGen
        run: brew install swiftgen

      - name: Cache Carthage
        uses: actions/cache@v4
        id: carthage-cache
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: ${{ runner.os }}-carthage-

      - name: Update Carthage
        run: carthage update --use-xcframeworks --cache-builds

      - name: Build
        run: |
          xcodebuild build \
            -project Swiftfin.xcodeproj \
            -scheme "Swiftfin tvOS" \
            -destination "platform=tvOS Simulator,name=${{ env.TVOS_SIMULATOR }}" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            | xcpretty && exit ${PIPESTATUS[0]}