name: "Build ðŸ”¨"

on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches: [ main ]

jobs:
  build:
    name: "Build ðŸ”¨"
    if: github.event.pull_request.draft == false
    runs-on: macos-15

    env:
      XCODE_VERSION: "16.4"
      TVOS_VERSION: "18"
      TVOS_SIMULATOR: "Apple TV 4K"

    steps:    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install SwiftGen
        run: brew install swiftgen

      - name: Cache Carthage
        uses: actions/cache@v4
        id: carthage-cache
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: ${{ runner.os }}-carthage-

      - name: Update Carthage
        run: carthage update --use-xcframeworks --cache-builds

      - name: Build
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 60
          command: sudo fastlane buildLane \
            scheme:"\"Swiftfin tvOS\"" \
            xcodeVersion:${{ env.XCODE_VERSION }}